# Generated by Django 3.0 on 2019-12-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiche', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='auteur',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='contenu',
            field=models.TextField(),
        ),
    ]
