# Generated by Django 3.0 on 2019-12-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiche', '0002_auto_20191217_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='date_crea',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='date_last_maj',
            field=models.CharField(max_length=30),
        ),
    ]
