# Generated by Django 2.2.7 on 2019-12-16 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('mail', models.CharField(max_length=50)),
                ('mot_de_passe', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=256)),
                ('categorie', models.CharField(max_length=30)),
                ('date_crea', models.DateField(max_length=10)),
                ('date_last_maj', models.DateField(max_length=10)),
                ('contenu', models.CharField(max_length=255)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiche.Auteur')),
            ],
        ),
    ]
